### ISSUE TITLE
Problems in build with K2

### ISSUE THREAD

**Issue by angelacorte** [Collektive/collektive-examples#35]
@danysk I have updated the dependencies of alchemist-incarnation-collektive into the [1.0.3](https://github.com/Collektive/alchemist-incarnation-collektive/releases/tag/1.0.3) (the latest one with K2) and Collektive into [2.0.1](https://github.com/Collektive/collektive/releases/tag/2.0.1) (same), but building gives the following error:
`org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Couldn't transform method node:
gradient (Lit/unibo/collektive/aggregate/AggregateContext;Lit/unibo/collektive/alchemist/device/DistanceSensor;Z)D:`

Refer to #34

**Comment by DanySK** [comment]
It looks nasty, and possibly related to context receivers.
I would first make sure that all kotlin dependencies use 1.9.20 (alchemist may be stuck to 1.9.10, maybe?)
https://scans.gradle.com/s/cukhzp44yrdac/build-dependencies?toggled=W1swXSxbMCwwXSxbMCwwLFs5XV0sWzAsMCxbOSw2M11dXQ

Then I would try to write an experiment that does not use context receivers

**Comment by angelacorte** [comment]
solved in #172
